# Generated by Django 3.1.4 on 2021-03-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('st_class', models.CharField(max_length=10)),
            ],
        ),
    ]
