# Generated by Django 3.1.4 on 2021-03-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210324_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
