# Generated by Django 3.1.4 on 2021-03-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210324_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='title',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
