# Generated by Django 3.1.4 on 2021-03-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210324_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='reg_no',
            new_name='regno',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='st_class',
            new_name='stclass',
        ),
    ]
